Consolidate reusable parameters and reusable objects.
OAI/sig-workflows pull request #182
Opened 2024-04-25 13:47 UTC by frankkilcommins

Simplified the referencing capabilities by consolidating `Reusable Parameter Object` into `Reusable Object`. This now means that there are two referencing mechanisms supported by the Workflows Specification:
- JSON Schema references using `$ref` keyword. This can only be used for JSON Schema - e.g. Inputs defined in components
- non JSON Schema referencing using the `Resuable Object` reference expression - e.g. all other component objects

closes #181

2024-04-25 18:07 UTC, kevinduffey commented on versions/1.0.0.md
> +<a name="workflowParameters"></a>parameters | [[Parameter Object](#parameter-object) \| [Reusable Object](#reusable-object)] | A list of parameters that are applicable for all steps described under t
"MUST link to parameters defined in." and below (line 338) you have "MUST link to a parameter". I would assume those should be the same wording? I assume a Reusable Object is single and should have one reference to one parameter (as stated in line 338)?

2024-04-29 01:02 UTC, adamaltman commented on versions/1.0.0.md
> +A simple object to allow referencing of objects contained within the [Components Object](#components-object). It can be leveraged from locations within steps or workflows in the Workflows Description
```suggestion
A simple object to allow referencing of objects contained within the [Components Object](#components-object). It can be used from locations within steps or workflows in the Workflows Description. **Note** - Input Objects MUST use standard JSON Schema referencing via the `$ref` keyword while all non JSON Schema objects use this object and its expression based referencing mechanism.

```
Isn't this going to confuse people that they can use `$ref` to reference most components in OpenAPI 3.1, 3.0, 2.0? Yet here, they have to distinguish if it's an input object? Is there a family of objects named input objects? (If so, it didn't stand out to me.)

2024-04-29 01:05 UTC, adamaltman commented on versions/1.0.0.md
> +<a name="reusableObjectValue"></a>value | `string` | A value which by default MUST override that of the referenced parameter. This is only applicable for parameter object references.
What does it mean "by default"? Are those words necessary? I wonder why this only applies to parameter object references?
```suggestion
<a name="reusableObjectValue"></a>value | `string` | Sets a value of the referenced parameter. This is only applicable for parameter object references.

```

2024-05-07 20:23 UTC, kevinduffey approved these changes

2024-05-08 16:27 UTC, ndenny requested changes

2024-05-08 16:27 UTC, ndenny commented on versions/1.0.0.md
> +    "value": 1
Suggest we make these consistent - JSON and YAML examples - this implies to me that JSON must have a `{` which is not true. (Same with the example above)

2024-05-17 15:46 UTC, ndenny approved these changes

2024-05-17 15:48 UTC, merged